package org.secondthought.countdoodle.util

/**
 * Curated emoji index used by [searchEmojis]. Covers common emojis with English
 * keywords. Not exhaustive — biased toward life events, dates, and milestones
 * since this app is a countdown / event tracker.
 */
val EMOJI_INDEX: List<EmojiEntry> = listOf(
    // Smileys & emotions
    EmojiEntry("😀", "grinning face", listOf("smile", "happy", "grin", "face")),
    EmojiEntry("😃", "smiling face", listOf("smile", "happy", "joy", "face")),
    EmojiEntry("😄", "smiling face open eyes", listOf("smile", "happy", "joy", "face")),
    EmojiEntry("😁", "beaming face", listOf("smile", "happy", "grin", "face")),
    EmojiEntry("😂", "tears of joy", listOf("laugh", "lol", "happy", "cry")),
    EmojiEntry("🤣", "rolling on the floor laughing", listOf("laugh", "lol", "rofl")),
    EmojiEntry("😊", "smiling face blush", listOf("smile", "happy", "blush")),
    EmojiEntry("😇", "smiling face halo", listOf("angel", "halo", "innocent")),
    EmojiEntry("🙂", "slightly smiling face", listOf("smile", "happy")),
    EmojiEntry("🙃", "upside down face", listOf("silly", "sarcasm")),
    EmojiEntry("😉", "winking face", listOf("wink", "flirt")),
    EmojiEntry("😌", "relieved face", listOf("relief", "calm")),
    EmojiEntry("😍", "smiling face with heart eyes", listOf("love", "heart", "crush")),
    EmojiEntry("🥰", "smiling face with hearts", listOf("love", "heart", "adore")),
    EmojiEntry("😘", "blowing a kiss", listOf("kiss", "love")),
    EmojiEntry("😗", "kissing face", listOf("kiss")),
    EmojiEntry("😋", "face savoring food", listOf("yum", "tasty", "delicious", "food")),
    EmojiEntry("😛", "tongue out", listOf("tongue", "playful")),
    EmojiEntry("😜", "winking tongue", listOf("tongue", "wink", "playful")),
    EmojiEntry("🤪", "zany face", listOf("crazy", "silly", "wild")),
    EmojiEntry("🤨", "raised eyebrow", listOf("skeptical", "doubt")),
    EmojiEntry("🧐", "monocle face", listOf("inspect", "examine", "smart")),
    EmojiEntry("🤓", "nerd face", listOf("nerd", "smart", "geek")),
    EmojiEntry("😎", "smiling face sunglasses", listOf("cool", "sunglasses")),
    EmojiEntry("🥳", "partying face", listOf("party", "birthday", "celebration", "hat")),
    EmojiEntry("🤩", "star struck", listOf("star", "excited", "wow")),
    EmojiEntry("🥺", "pleading face", listOf("plead", "puppy", "beg")),
    EmojiEntry("😢", "crying face", listOf("cry", "sad", "tear")),
    EmojiEntry("😭", "loudly crying face", listOf("cry", "sob", "sad")),
    EmojiEntry("😡", "pouting face", listOf("angry", "mad", "rage")),
    EmojiEntry("😱", "screaming in fear", listOf("shock", "scream", "scared")),
    EmojiEntry("🤔", "thinking face", listOf("think", "ponder", "hmm")),
    EmojiEntry("😴", "sleeping face", listOf("sleep", "tired", "zzz")),
    EmojiEntry("🤗", "hugging face", listOf("hug", "embrace")),
    EmojiEntry("🙏", "folded hands", listOf("pray", "thanks", "please")),
    EmojiEntry("👍", "thumbs up", listOf("yes", "approve", "like", "good")),
    EmojiEntry("👎", "thumbs down", listOf("no", "disapprove", "dislike", "bad")),
    EmojiEntry("👏", "clapping hands", listOf("clap", "applause", "bravo")),
    EmojiEntry("🙌", "raising hands", listOf("celebrate", "praise", "yay")),
    EmojiEntry("💪", "flexed biceps", listOf("strong", "muscle", "flex", "workout")),
    EmojiEntry("✌️", "victory hand", listOf("peace", "victory")),
    EmojiEntry("🤞", "crossed fingers", listOf("luck", "hope", "wish")),
    EmojiEntry("👋", "waving hand", listOf("hello", "wave", "bye", "goodbye")),

    // Hearts & symbols
    EmojiEntry("❤️", "red heart", listOf("love", "heart")),
    EmojiEntry("🧡", "orange heart", listOf("love", "heart")),
    EmojiEntry("💛", "yellow heart", listOf("love", "heart")),
    EmojiEntry("💚", "green heart", listOf("love", "heart")),
    EmojiEntry("💙", "blue heart", listOf("love", "heart")),
    EmojiEntry("💜", "purple heart", listOf("love", "heart")),
    EmojiEntry("🖤", "black heart", listOf("love", "heart")),
    EmojiEntry("🤍", "white heart", listOf("love", "heart")),
    EmojiEntry("💖", "sparkling heart", listOf("love", "heart", "sparkle")),
    EmojiEntry("💕", "two hearts", listOf("love", "heart")),
    EmojiEntry("💔", "broken heart", listOf("breakup", "heartbreak", "sad")),
    EmojiEntry("💯", "hundred points", listOf("perfect", "100", "score")),
    EmojiEntry("⭐", "star", listOf("favorite", "star")),
    EmojiEntry("🌟", "glowing star", listOf("star", "sparkle", "shine")),
    EmojiEntry("✨", "sparkles", listOf("sparkle", "shine", "magic")),
    EmojiEntry("⚡", "high voltage", listOf("lightning", "electric", "energy", "fast")),
    EmojiEntry("🔥", "fire", listOf("fire", "hot", "lit", "flame")),
    EmojiEntry("🎯", "bullseye", listOf("target", "goal", "aim", "dart")),
    EmojiEntry("✅", "check mark", listOf("done", "yes", "correct", "ok")),
    EmojiEntry("❌", "cross mark", listOf("no", "wrong", "x", "incorrect")),
    EmojiEntry("❓", "question mark", listOf("question", "ask", "huh")),
    EmojiEntry("❗", "exclamation", listOf("important", "alert", "warning")),

    // Celebrations & events
    EmojiEntry("🎉", "party popper", listOf("party", "celebration", "tada", "confetti")),
    EmojiEntry("🎊", "confetti ball", listOf("party", "celebration", "confetti")),
    EmojiEntry("🎂", "birthday cake", listOf("birthday", "cake", "party", "candle")),
    EmojiEntry("🍰", "shortcake", listOf("cake", "dessert", "slice")),
    EmojiEntry("🧁", "cupcake", listOf("cake", "dessert", "sweet")),
    EmojiEntry("🎁", "wrapped gift", listOf("present", "gift", "birthday", "christmas")),
    EmojiEntry("🎈", "balloon", listOf("party", "birthday", "celebration")),
    EmojiEntry("🎀", "ribbon", listOf("bow", "gift", "decoration")),
    EmojiEntry("🥂", "clinking glasses", listOf("toast", "cheers", "champagne", "celebration")),
    EmojiEntry("🍾", "bottle with popping cork", listOf("champagne", "celebration", "new year")),
    EmojiEntry("🎆", "fireworks", listOf("fireworks", "new year", "celebration")),
    EmojiEntry("🎇", "sparkler", listOf("fireworks", "sparkle", "celebration")),
    EmojiEntry("💍", "ring", listOf("ring", "engagement", "wedding", "marriage", "diamond")),
    EmojiEntry("💒", "wedding", listOf("wedding", "marriage", "church")),
    EmojiEntry("👰", "bride", listOf("wedding", "bride", "marriage")),
    EmojiEntry("🤵", "groom", listOf("wedding", "groom", "marriage")),
    EmojiEntry("💐", "bouquet", listOf("flowers", "wedding", "anniversary")),
    EmojiEntry("🎓", "graduation cap", listOf("graduation", "school", "graduate", "diploma")),
    EmojiEntry("👶", "baby", listOf("baby", "infant", "newborn")),
    EmojiEntry("🤰", "pregnant", listOf("pregnant", "baby", "expecting")),
    EmojiEntry("🎄", "christmas tree", listOf("christmas", "tree", "xmas", "holiday")),
    EmojiEntry("🎃", "jack o lantern", listOf("halloween", "pumpkin", "spooky")),
    EmojiEntry("🦃", "turkey", listOf("thanksgiving", "turkey")),
    EmojiEntry("🐰", "rabbit face", listOf("easter", "bunny", "rabbit")),
    EmojiEntry("🎅", "santa claus", listOf("christmas", "santa", "xmas")),
    EmojiEntry("🕯️", "candle", listOf("candle", "flame", "light")),
    EmojiEntry("🪅", "pinata", listOf("party", "pinata", "celebration")),

    // Time & calendar
    EmojiEntry("⏰", "alarm clock", listOf("alarm", "clock", "time", "wake")),
    EmojiEntry("⏳", "hourglass", listOf("time", "wait", "hourglass")),
    EmojiEntry("⌛", "hourglass done", listOf("time", "done", "hourglass")),
    EmojiEntry("⏱️", "stopwatch", listOf("timer", "stopwatch", "time")),
    EmojiEntry("🕐", "clock", listOf("clock", "time", "hour")),
    EmojiEntry("📅", "calendar", listOf("calendar", "date", "schedule")),
    EmojiEntry("📆", "tear off calendar", listOf("calendar", "date", "schedule")),
    EmojiEntry("🗓️", "spiral calendar", listOf("calendar", "schedule", "planner")),

    // Food & drink
    EmojiEntry("🍕", "pizza", listOf("pizza", "food", "italian")),
    EmojiEntry("🍔", "hamburger", listOf("burger", "food")),
    EmojiEntry("🌭", "hot dog", listOf("hotdog", "food")),
    EmojiEntry("🌮", "taco", listOf("taco", "food", "mexican")),
    EmojiEntry("🍣", "sushi", listOf("sushi", "food", "japanese")),
    EmojiEntry("🍜", "ramen", listOf("noodles", "ramen", "soup", "food")),
    EmojiEntry("🍦", "ice cream", listOf("ice cream", "dessert", "sweet")),
    EmojiEntry("🍩", "doughnut", listOf("donut", "doughnut", "dessert")),
    EmojiEntry("🍪", "cookie", listOf("cookie", "dessert", "snack")),
    EmojiEntry("🍫", "chocolate", listOf("chocolate", "dessert", "candy")),
    EmojiEntry("🍿", "popcorn", listOf("popcorn", "movie", "snack")),
    EmojiEntry("🍎", "red apple", listOf("apple", "fruit")),
    EmojiEntry("🍌", "banana", listOf("banana", "fruit")),
    EmojiEntry("🍓", "strawberry", listOf("strawberry", "fruit", "berry")),
    EmojiEntry("🍇", "grapes", listOf("grapes", "fruit", "wine")),
    EmojiEntry("🍉", "watermelon", listOf("watermelon", "fruit", "summer")),
    EmojiEntry("☕", "hot beverage", listOf("coffee", "tea", "drink")),
    EmojiEntry("🍵", "tea", listOf("tea", "drink", "matcha")),
    EmojiEntry("🍺", "beer", listOf("beer", "drink", "alcohol")),
    EmojiEntry("🍷", "wine glass", listOf("wine", "drink", "alcohol")),
    EmojiEntry("🍸", "cocktail", listOf("cocktail", "drink", "martini")),

    // Activities & sports
    EmojiEntry("⚽", "soccer ball", listOf("soccer", "football", "sport")),
    EmojiEntry("🏀", "basketball", listOf("basketball", "sport")),
    EmojiEntry("🏈", "american football", listOf("football", "sport")),
    EmojiEntry("⚾", "baseball", listOf("baseball", "sport")),
    EmojiEntry("🎾", "tennis", listOf("tennis", "sport")),
    EmojiEntry("🏐", "volleyball", listOf("volleyball", "sport")),
    EmojiEntry("🏓", "ping pong", listOf("ping pong", "table tennis", "sport")),
    EmojiEntry("🏸", "badminton", listOf("badminton", "sport")),
    EmojiEntry("🥊", "boxing glove", listOf("boxing", "fight", "sport")),
    EmojiEntry("🏆", "trophy", listOf("trophy", "winner", "award", "champion")),
    EmojiEntry("🥇", "gold medal", listOf("gold", "medal", "first", "winner")),
    EmojiEntry("🥈", "silver medal", listOf("silver", "medal", "second")),
    EmojiEntry("🥉", "bronze medal", listOf("bronze", "medal", "third")),
    EmojiEntry("🏅", "sports medal", listOf("medal", "award", "sports")),
    EmojiEntry("🎖️", "military medal", listOf("medal", "honor")),
    EmojiEntry("🏃", "person running", listOf("run", "running", "exercise", "race")),
    EmojiEntry("🚴", "person biking", listOf("bike", "cycling", "bicycle")),
    EmojiEntry("🏊", "person swimming", listOf("swim", "swimming", "pool")),
    EmojiEntry("🧘", "person in lotus", listOf("yoga", "meditation", "calm")),
    EmojiEntry("🎮", "video game", listOf("game", "gaming", "controller", "video")),
    EmojiEntry("🎲", "dice", listOf("dice", "game", "luck")),
    EmojiEntry("🎨", "artist palette", listOf("art", "paint", "palette")),
    EmojiEntry("🎬", "clapper board", listOf("movie", "film", "cinema")),
    EmojiEntry("🎤", "microphone", listOf("mic", "sing", "karaoke")),
    EmojiEntry("🎧", "headphones", listOf("music", "headphones", "audio")),
    EmojiEntry("🎵", "musical note", listOf("music", "note", "song")),
    EmojiEntry("🎶", "musical notes", listOf("music", "notes", "song")),
    EmojiEntry("🎸", "guitar", listOf("guitar", "music", "instrument")),
    EmojiEntry("🎹", "piano", listOf("piano", "music", "instrument", "keyboard")),
    EmojiEntry("🎺", "trumpet", listOf("trumpet", "music", "instrument")),
    EmojiEntry("🥁", "drum", listOf("drum", "music", "instrument")),
    EmojiEntry("📚", "books", listOf("book", "books", "read", "study", "library")),
    EmojiEntry("📖", "open book", listOf("book", "read", "study")),

    // Travel & places
    EmojiEntry("✈️", "airplane", listOf("plane", "flight", "travel", "trip")),
    EmojiEntry("🚗", "car", listOf("car", "drive", "auto")),
    EmojiEntry("🚕", "taxi", listOf("taxi", "cab", "car")),
    EmojiEntry("🚙", "suv", listOf("car", "suv", "drive")),
    EmojiEntry("🚌", "bus", listOf("bus", "transport")),
    EmojiEntry("🚆", "train", listOf("train", "transport", "rail")),
    EmojiEntry("🚇", "metro", listOf("subway", "metro", "train")),
    EmojiEntry("🚢", "ship", listOf("ship", "boat", "cruise")),
    EmojiEntry("⛵", "sailboat", listOf("boat", "sail", "sailing")),
    EmojiEntry("🚀", "rocket", listOf("rocket", "launch", "space", "fast")),
    EmojiEntry("🛸", "ufo", listOf("ufo", "alien", "space")),
    EmojiEntry("🏖️", "beach", listOf("beach", "vacation", "sand", "sea")),
    EmojiEntry("🏝️", "desert island", listOf("island", "tropical", "beach")),
    EmojiEntry("🏔️", "mountain", listOf("mountain", "snow", "peak")),
    EmojiEntry("🗻", "mount fuji", listOf("mountain", "fuji")),
    EmojiEntry("🏕️", "camping", listOf("camp", "camping", "tent")),
    EmojiEntry("🎡", "ferris wheel", listOf("fair", "carnival", "amusement")),
    EmojiEntry("🎢", "roller coaster", listOf("rollercoaster", "amusement", "park")),
    EmojiEntry("🗽", "statue of liberty", listOf("liberty", "new york", "usa")),
    EmojiEntry("🗼", "tokyo tower", listOf("tower", "tokyo", "japan")),
    EmojiEntry("🏰", "castle", listOf("castle", "fairytale")),
    EmojiEntry("🏠", "house", listOf("home", "house", "building")),
    EmojiEntry("🏡", "house with garden", listOf("home", "house", "garden")),
    EmojiEntry("🏢", "office building", listOf("office", "work", "building")),
    EmojiEntry("🏥", "hospital", listOf("hospital", "doctor", "medical")),
    EmojiEntry("🏫", "school", listOf("school", "education")),
    EmojiEntry("🌍", "globe europe africa", listOf("earth", "world", "globe")),
    EmojiEntry("🌎", "globe americas", listOf("earth", "world", "globe", "americas")),
    EmojiEntry("🌏", "globe asia australia", listOf("earth", "world", "globe", "asia")),

    // Nature & weather
    EmojiEntry("☀️", "sun", listOf("sun", "sunny", "weather")),
    EmojiEntry("🌤️", "sun behind cloud", listOf("sun", "cloud", "weather")),
    EmojiEntry("☁️", "cloud", listOf("cloud", "weather")),
    EmojiEntry("🌧️", "rain", listOf("rain", "weather", "storm")),
    EmojiEntry("⛈️", "thunderstorm", listOf("storm", "rain", "thunder", "weather")),
    EmojiEntry("🌩️", "lightning", listOf("lightning", "storm", "weather")),
    EmojiEntry("🌨️", "snow", listOf("snow", "winter", "weather")),
    EmojiEntry("❄️", "snowflake", listOf("snow", "winter", "cold", "snowflake")),
    EmojiEntry("☃️", "snowman", listOf("snow", "winter", "snowman")),
    EmojiEntry("⛄", "snowman without snow", listOf("snowman", "winter")),
    EmojiEntry("🌈", "rainbow", listOf("rainbow", "pride", "colorful")),
    EmojiEntry("🌊", "wave", listOf("wave", "ocean", "water", "sea")),
    EmojiEntry("🌙", "crescent moon", listOf("moon", "night")),
    EmojiEntry("🌝", "full moon face", listOf("moon", "full")),
    EmojiEntry("🌞", "sun face", listOf("sun")),
    EmojiEntry("🌸", "cherry blossom", listOf("flower", "spring", "sakura", "cherry")),
    EmojiEntry("🌺", "hibiscus", listOf("flower", "tropical")),
    EmojiEntry("🌻", "sunflower", listOf("flower", "sunflower")),
    EmojiEntry("🌷", "tulip", listOf("flower", "tulip", "spring")),
    EmojiEntry("🌹", "rose", listOf("flower", "rose", "love")),
    EmojiEntry("🌳", "tree", listOf("tree", "forest", "nature")),
    EmojiEntry("🌲", "evergreen tree", listOf("tree", "pine", "christmas")),
    EmojiEntry("🌴", "palm tree", listOf("palm", "tree", "tropical")),
    EmojiEntry("🍀", "four leaf clover", listOf("luck", "clover", "irish", "shamrock")),
    EmojiEntry("🍁", "maple leaf", listOf("leaf", "maple", "fall", "autumn")),

    // Animals
    EmojiEntry("🐶", "dog face", listOf("dog", "puppy", "animal", "pet")),
    EmojiEntry("🐱", "cat face", listOf("cat", "kitten", "animal", "pet")),
    EmojiEntry("🐭", "mouse face", listOf("mouse", "animal")),
    EmojiEntry("🐹", "hamster", listOf("hamster", "animal", "pet")),
    EmojiEntry("🐰", "rabbit face", listOf("rabbit", "bunny", "animal")),
    EmojiEntry("🦊", "fox", listOf("fox", "animal")),
    EmojiEntry("🐻", "bear", listOf("bear", "animal")),
    EmojiEntry("🐼", "panda", listOf("panda", "animal")),
    EmojiEntry("🐨", "koala", listOf("koala", "animal")),
    EmojiEntry("🐯", "tiger face", listOf("tiger", "animal")),
    EmojiEntry("🦁", "lion", listOf("lion", "animal")),
    EmojiEntry("🐮", "cow face", listOf("cow", "animal")),
    EmojiEntry("🐷", "pig face", listOf("pig", "animal")),
    EmojiEntry("🐸", "frog", listOf("frog", "animal")),
    EmojiEntry("🐵", "monkey face", listOf("monkey", "animal")),
    EmojiEntry("🐔", "chicken", listOf("chicken", "animal", "bird")),
    EmojiEntry("🐧", "penguin", listOf("penguin", "animal", "bird")),
    EmojiEntry("🐦", "bird", listOf("bird", "animal")),
    EmojiEntry("🦄", "unicorn", listOf("unicorn", "fantasy", "animal")),
    EmojiEntry("🐝", "bee", listOf("bee", "honey", "insect")),
    EmojiEntry("🦋", "butterfly", listOf("butterfly", "insect")),
    EmojiEntry("🐢", "turtle", listOf("turtle", "animal", "slow")),
    EmojiEntry("🐬", "dolphin", listOf("dolphin", "animal", "sea")),
    EmojiEntry("🐳", "whale", listOf("whale", "animal", "sea")),
    EmojiEntry("🐠", "tropical fish", listOf("fish", "animal", "tropical")),
    EmojiEntry("🦈", "shark", listOf("shark", "animal", "sea")),

    // Objects & work
    EmojiEntry("💻", "laptop", listOf("computer", "laptop", "work")),
    EmojiEntry("📱", "phone", listOf("phone", "mobile", "cell")),
    EmojiEntry("📷", "camera", listOf("camera", "photo")),
    EmojiEntry("📺", "tv", listOf("tv", "television")),
    EmojiEntry("📰", "newspaper", listOf("newspaper", "news")),
    EmojiEntry("✏️", "pencil", listOf("pencil", "write", "edit")),
    EmojiEntry("📝", "memo", listOf("note", "memo", "write", "list")),
    EmojiEntry("📌", "pushpin", listOf("pin", "pushpin", "important")),
    EmojiEntry("📎", "paperclip", listOf("paperclip", "attach")),
    EmojiEntry("💼", "briefcase", listOf("work", "briefcase", "business")),
    EmojiEntry("💰", "money bag", listOf("money", "cash", "wealth")),
    EmojiEntry("💵", "dollar", listOf("money", "dollar", "cash")),
    EmojiEntry("💳", "credit card", listOf("card", "credit", "money", "pay")),
    EmojiEntry("🔑", "key", listOf("key", "unlock")),
    EmojiEntry("🔒", "lock", listOf("lock", "secure", "private")),
    EmojiEntry("🔔", "bell", listOf("bell", "notification", "alert")),
    EmojiEntry("📞", "telephone", listOf("phone", "call", "telephone")),
    EmojiEntry("📧", "email", listOf("email", "mail", "message")),
    EmojiEntry("💡", "light bulb", listOf("idea", "light", "bulb")),
    EmojiEntry("🔦", "flashlight", listOf("flashlight", "torch", "light")),
    EmojiEntry("🛒", "shopping cart", listOf("shopping", "cart", "buy")),
    EmojiEntry("🛍️", "shopping bags", listOf("shopping", "bags", "buy")),

    // Misc useful
    EmojiEntry("🌍", "earth", listOf("earth", "world", "planet")),
    EmojiEntry("🚨", "police light", listOf("alert", "siren", "emergency")),
    EmojiEntry("🚫", "no entry", listOf("no", "forbidden", "ban")),
    EmojiEntry("⚠️", "warning", listOf("warning", "caution", "alert")),
)
